/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _IndexRoute } from '../pages/';
import { Route as _Events_IdRoute } from '../pages/events/[id]';
import { Route as _ExploreRoute } from '../pages/explore';
import { Route as _NearbyRoute } from '../pages/nearby';
import { Route as _HotRoute } from '../pages/hot';
import { Route as _EndingRoute } from '../pages/ending';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/events/:id': (typeof _Events_IdRoute)['_inputType'];
    '/explore': (typeof _ExploreRoute)['_inputType'];
    '/nearby': (typeof _NearbyRoute)['_inputType'];
    '/hot': (typeof _HotRoute)['_inputType'];
    '/ending': (typeof _EndingRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/events/:id': (typeof _Events_IdRoute)['_outputType'];
    '/explore': (typeof _ExploreRoute)['_outputType'];
    '/nearby': (typeof _NearbyRoute)['_outputType'];
    '/hot': (typeof _HotRoute)['_outputType'];
    '/ending': (typeof _EndingRoute)['_outputType'];
  }
}
