/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _EventsIdRoute } from '../pages/events/[id]';
import { Route as _IndexRoute } from '../pages/';
import { Route as _MypageLikesRoute } from '../pages/mypage/likes';
import { Route as _MypageRecentRoute } from '../pages/mypage/recent';
import { Route as _MypageTicketsRoute } from '../pages/mypage/tickets';
import { Route as _MypageRoute } from '../pages/mypage';
import { Route as _PointsRoute } from '../pages/points';
import { Route as _SavedRoute } from '../pages/saved';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/events/:id': (typeof _EventsIdRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/mypage/likes': (typeof _MypageLikesRoute)['_inputType'];
    '/mypage/recent': (typeof _MypageRecentRoute)['_inputType'];
    '/mypage/tickets': (typeof _MypageTicketsRoute)['_inputType'];
    '/mypage': (typeof _MypageRoute)['_inputType'];
    '/points': (typeof _PointsRoute)['_inputType'];
    '/saved': (typeof _SavedRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/events/:id': (typeof _EventsIdRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/mypage/likes': (typeof _MypageLikesRoute)['_outputType'];
    '/mypage/recent': (typeof _MypageRecentRoute)['_outputType'];
    '/mypage/tickets': (typeof _MypageTicketsRoute)['_outputType'];
    '/mypage': (typeof _MypageRoute)['_outputType'];
    '/points': (typeof _PointsRoute)['_outputType'];
    '/saved': (typeof _SavedRoute)['_outputType'];
  }
}
